export enum ReasonCode {
  ELIGIBLE = "ELIGIBLE",
  OWNED = "OWNED",
  EARNED = "EARNED",
  CLAIMABLE = "CLAIMABLE",

  INSUFFICIENT_CURRENCY = "INSUFFICIENT_CURRENCY",
  MISSING_PREREQUISITE = "MISSING_PREREQUISITE",
  NODE_INACTIVE = "NODE_INACTIVE",
  BADGE_INACTIVE = "BADGE_INACTIVE",
  ALREADY_OWNED = "ALREADY_OWNED",
  ALREADY_EARNED = "ALREADY_EARNED",
  CRITERIA_NOT_MET = "CRITERIA_NOT_MET",
  THRESHOLD_NOT_MET = "THRESHOLD_NOT_MET",
  THRESHOLD_MET = "THRESHOLD_MET",
  NO_NEXT_RANK = "NO_NEXT_RANK",
  PREREQUISITE_NOT_OWNED = "PREREQUISITE_NOT_OWNED",
}
